# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Wonseo MO
baseurl:        ""
url:            "https://github.com/mws8846"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Wonseo MO
  url:          https://github.com/mws8846
  email:        mws8846@gmail.com
  github:       mws8846
  twitter:      mws8846

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/mws8846/mws8846.github.io
